---
## namenode IP from host file
#namenodeip: "{{ hostvars [namenode]['ansible_default_ipv4']['address'] }}"
#namenodeip: "{{ groups[ 'namenode' ] }}"    
namenodeip: "{{ hostvars [ groups['namenode' ]]['ansible_default_ipv4']['address'] }}" 
